const styles = {
    
    container: {
        display: "flex",
        position: "relative",
        flexDirection: "row",
        minHeight: "100vh",
        width: "100%",
        overflow: "hidden",
        },
    scoreboard: {
        padding: "2%",
        transition: "transform 0.5s ease",
        overflow:"hidden",
        },
    chatWindow: {
        display: "flex",
        flexDirection: "column",
        justifyContent:"space-between",
        padding: "10px",
        width:"100%",
        alignItems:"center",
        transition: "transform 0.5s ease",

    },
    WelcomechatArea: {
        display:"flex",
        flexDirection:"column",
        justifyContent:"center",
        overflowY: "auto",
        width:"85%",
        alignItems:"center",
        // padding: "10px",
        boxSizing: "border-box",
        height: "calc(100vh - 125px)", // Adjust height to account for input area
        },
    chatArea: {
        justifyContent:"center",
        overflowY: "auto",
        width:"85%",
        alignItems:"center",
        // padding: "10px",
        boxSizing: "border-box",
        height: "calc(100vh - 125px)", // Adjust height to account for input area
        },
    inputArea: {
        display: "flex",
        width:"85%",
        alignItems: "center", 
        backgroundColor: "#f7f7f7",
        padding: "10px ",
        height:"70px",
        boxSizing: "border-box",
        borderRadius: "25px", 
        marginBottom:"10px",
        },
    input: {
        flex: 1,
        border: "none", 
        outline: "none", 
        fontSize: "16px",
        backgroundColor: "transparent", 
        textAlign: "left", 
        },
    iconButton: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#000",
        color: "#fff",
        borderRadius: "50%",
        width: "40px",
        height: "40px",
        cursor: "pointer",
        },
    submit: {
        display: "flex",
        justifyContent:"flex-end",
        width:"84.6%",
        alignItems: "right", 
        height:"70px",
        borderRadius: "25px", 
        },
    submitButton: {
        display:"flex",
        padding: "10px 20px",
        justifyContent:"flex-end",
        // bottom: "20px",
        backgroundColor: "#28a745",
        color: "white",
        border: "none",
        borderRadius: "5px",
        boxSizing: "border-box",
        cursor: "pointer",
        },

    questionBlock: {
        marginBottom: "10px",
        width: "100%",
        padding: "10px",
        backgroundColor: "#f9f9f9",
        borderRadius: "5px",
        boxSizing: "border-box",
    },
    messageBlock: {
        marginBottom: "10px",
        boxSizing: "border-box",
    },
    userBlock: {
        display:"flex",
        justifyContent:"flex-end",
        boxSizing: "border-box",
        marginRight:"10px",
        
    },
    welcomeMessage: {
        display:"flex",
        flexDirection:"column",
        justifyContent:"center",
        textAlign: "center",
        width:"100%",
    },
    generatingMessage: {
        // display: 'flex',
        // justifyContent: 'center',
        // alignItems: 'center',
        // padding: '10px',
        // backgroundColor: '#f0f0f0',
        // borderRadius: '5px',
        // marginBottom: '10px',
    },
    ellipsis: {
        display: 'inline-block',
        width: '1em',
        textAlign: 'left',
        // animation: 'ellipsis-animation 2.0s infinite',
        animation: 'dotAnimation 1.5s steps(1) infinite',
    },
    '@keyframes ellipsis-animation': {
        '0%': { content: '"."' },
        '33%': { content: '".."' },
        '66%': { content: '"..."' },
        '100%': { content: '"."' },
    },
    };
export default styles;